services:
  redis:
    build:
      context: .
      dockerfile: ./redis-dockerfile
    container_name: asyncq-redis
    restart: always
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - ./data:/data
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_PORT=${REDIS_PORT}
